# Generated by Django 3.0.4 on 2020-03-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_safe', models.CharField(max_length=50)),
                ('fish_in_lake', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fish', to='fishbytes.Fish')),
            ],
        ),
    ]
