# Generated by Django 3.0.4 on 2020-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0002_auto_20200324_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='identifiers',
            field=models.CharField(default=None, max_length=350, null=True),
        ),
    ]
