# Generated by Django 3.0.4 on 2020-03-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0003_auto_20200324_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulations',
            name='daily_total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regulations',
            name='size_max',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regulations',
            name='size_min',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regulations',
            name='weight_max',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regulations',
            name='weight_min',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
