# Generated by Django 3.0.4 on 2020-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0004_auto_20200324_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakes',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
