# Generated by Django 3.0.4 on 2020-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0005_lakes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='fish',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
