# Generated by Django 3.0.4 on 2020-03-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0006_auto_20200325_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fish',
            name='fish_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishbytes.Tag'),
        ),
        migrations.AddField(
            model_name='lakes',
            name='lake_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishbytes.Tag'),
        ),
    ]
