# Generated by Django 3.0.4 on 2020-03-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0007_auto_20200325_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_safe', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Regulations',
            new_name='Regulation',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='fish_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='found_in',
        ),
        migrations.DeleteModel(
            name='Lakes',
        ),
        migrations.AddField(
            model_name='lake',
            name='fish_in_lake',
            field=models.ManyToManyField(related_name='lake', to='fishbytes.Fish'),
        ),
        migrations.AddField(
            model_name='lake',
            name='lake_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishbytes.Tag'),
        ),
        migrations.AddField(
            model_name='fish',
            name='found_in',
            field=models.ManyToManyField(related_name='fish', to='fishbytes.Lake'),
        ),
    ]
