# Generated by Django 3.0.4 on 2020-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0008_auto_20200326_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='found_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='fish', to='fishbytes.Lake'),
        ),
    ]
