# Generated by Django 3.0.4 on 2020-03-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0010_remove_fish_found_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='lake',
            name='fish_in_lake',
            field=models.ManyToManyField(related_name='fishes', to='fishbytes.Fish'),
        ),
    ]
