# Generated by Django 3.0.4 on 2020-03-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0011_auto_20200327_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='fish_in_lake',
            field=models.ManyToManyField(related_name='lakes', to='fishbytes.Fish'),
        ),
    ]
