# Generated by Django 3.0.4 on 2020-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0012_auto_20200327_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='img',
            field=models.ImageField(default='default.png', upload_to='static/'),
        ),
    ]
