# Generated by Django 3.0.4 on 2020-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0014_auto_20200328_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media/'),
        ),
    ]
