# Generated by Django 3.0.4 on 2020-03-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0015_auto_20200328_1649'),
        ('fishbytes', '0013_catch'),
    ]

    operations = [
    ]
