# Generated by Django 3.0.4 on 2020-03-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0013_catch'),
        ('fishbytes', '0015_auto_20200328_1649'),
    ]

    operations = [
    ]
