# Generated by Django 3.0.4 on 2020-03-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0016_merge_20200328_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='img',
            field=models.ImageField(upload_to='fish/'),
        ),
    ]
