# Generated by Django 3.0.4 on 2020-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0017_auto_20200328_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
