# Generated by Django 3.0.4 on 2020-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0018_auto_20200328_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='identifiers',
            field=models.TextField(default=None, max_length=550, null=True),
        ),
    ]
