# Generated by Django 3.0.4 on 2020-03-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0016_merge_20200328_2039'),
        ('fishbytes', '0018_auto_20200328_2106'),
    ]

    operations = [
    ]
