# Generated by Django 3.0.4 on 2020-03-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0017_auto_20200328_2049'),
        ('fishbytes', '0020_question'),
    ]

    operations = [
    ]
