# Generated by Django 3.0.4 on 2020-03-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0021_merge_20200328_2332'),
        ('fishbytes', '0019_auto_20200330_1549'),
    ]

    operations = [
    ]
