# Generated by Django 3.0.4 on 2020-03-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0022_merge_20200330_1808'),
        ('fishbytes', '0022_merge_20200330_1818'),
    ]

    operations = [
    ]
