# Generated by Django 3.0.4 on 2020-03-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0022_merge_20200330_1807'),
        ('fishbytes', '0023_merge_20200330_1855'),
    ]

    operations = [
    ]
