# Generated by Django 3.0.5 on 2020-04-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0024_merge_20200331_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='img',
            field=models.ImageField(default='default.png', upload_to='lake/'),
        ),
    ]
