# Generated by Django 3.0.5 on 2020-04-02 21:30

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0025_auto_20200401_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='record',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lake',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
    ]
