# Generated by Django 3.0.5 on 2020-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0025_auto_20200401_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
