# Generated by Django 3.0.5 on 2020-04-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0027_auto_20200402_2217'),
        ('fishbytes', '0026_auto_20200402_2245'),
    ]

    operations = [
    ]
