# Generated by Django 3.0.5 on 2020-04-03 22:37

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0028_merge_20200403_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='lake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fishbytes.Lake'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [0, 0]}, null=True),
        ),
    ]
