# Generated by Django 3.0.5 on 2020-04-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0030_auto_20200403_2240'),
        ('fishbytes', '0028_merge_20200403_1727'),
    ]

    operations = [
    ]
