# Generated by Django 3.0.5 on 2020-04-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishbytes', '0031_merge_20200406_1658'),
        ('fishbytes', '0031_merge_20200404_0023'),
    ]

    operations = [
    ]
